name: Deploy
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Test Scripts
        run: npm run test

      - name: Printing Test Results
        run: echo "Testing Completed Successfully"

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Lint Scripts
        run: npm run lint

      - name: Printing Linting Results
        run: echo "Linting done Successfully"

  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Build Script
        run: npm run build
      
      - name: Printing Deployment Results
        run: echo "Application Deployed Successfully"