name: Deploying Sequentially
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Test Scripts
        run: npm run test

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifacts
          path: dist

      - name: Printing Test Results
        run: echo "Testing Completed Successfully"

  Linting:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci
      
      - name: Downloading Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: Artifacts
          path: dist

      - name: Running Lint Scripts
        run: npm run lint

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifacts
          path: dist

      - name: Printing Linting Results
        run: echo "Linting done Successfully"

  Deploying:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Build Script
        run: npm run build

      - name: Downloading Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: Artifacts
          path: dist
        
      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifacts
          path: dist
          
      - name: Printing Deployment Results
        run: echo "Application Deployed Successfully"
