name: Deploy
on: [workflow_dispatch, push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Test Script
        run: npm run test

      - name: Printing The Output on Successful Testing Completion
        run: echo "Testing Completed Successfully"

  linting:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2
      
      - name: Installing Dependencies
        run: npm ci
      
      - name: Running Lint Script
        run: npm run lint
      
      - name: Printing The Output on Successful Linting Completion
        run: echo "Linting Completed Successfully"

  building:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v3.5.2
      
      - name: Installing Dependencies
        run: npm ci
      
      - name: Running Build Script
        run: npm run build
      
      - name: Printing The Output on Successful Deployment Completion
        run: echo "Deployment Completed Successfully"
